name: Linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FORCE_COLOR: 1

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run ESLint
        run: |
          cd frontend
          npm run lint
  nodechecker:
    name: Node Modules Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then 
            echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."
            echo -e "\e[1;32mYou can set up a .gitignore file with this folder included to prevent this from happening in the future." 
            exit 1; 
          fi